# .gitlab-ci.yml

image: node:16

stages:
  - test
  - build
    # - deploy

before_script:
  - npm config set registry https://registry.npmmirror.com/
  - npm install

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm run lint
# deploy:
#   stage: deploy
#   script:
#     - scp -r build/ user@example.com:/path/to/destination/folder/
#   only:
#     - master  # 只有在 master 分支上触发部署
