# .gitlab-ci.yml

image: node:20-alpine

stages:
  - test
  - build
    # - deploy

before_script:
  - npm config set registry https://registry.npmmirror.com/
  - npm install pnpm -g
  - pnpm config set store-dir .pnpm-store
  - pnpm i --no-frozen-lockfile

# cache:
#   paths:
#     - .pnpm-store

build:
  stage: build
  script:
    - pnpm run build
  # artifacts:
  #   paths:
  #     - dist/

test:
  stage: test
  script:
    - pnpm run lint
# deploy:
#   stage: deploy
#   script:
#     - scp -r build/ user@example.com:/path/to/destination/folder/
#   only:
#     - master  # 只有在 master 分支上触发部署
